version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - $PWD/postgres:/data/postgres
      - $PWD/postgres-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - $PWD/postgres-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - "5432:5432"
    networks:
      postgres:
        ipv4_address: 172.33.1.1
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - $PWD/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      postgres:
        ipv4_address: 172.33.1.2
    restart: unless-stopped

networks:
  postgres:
    name: postgres
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16
volumes:
    postgres:
    pgadmin:
